INSERT INTO ROL (TIPO) VALUES ('ADMIN');
INSERT INTO ROL (TIPO) VALUES ('USER');
INSERT INTO ROL (TIPO) VALUES ('CREADOR');
INSERT INTO ROL (TIPO) VALUES ('TELEOPERADOR');
INSERT INTO ROL (TIPO) VALUES ('ANALISTA');

INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('admin@gmail.com', 'admin', 1);
