INSERT INTO ROL (TIPO) VALUES ('ADMIN');
INSERT INTO ROL (TIPO) VALUES ('USER');
INSERT INTO ROL (TIPO) VALUES ('CREADOR');
INSERT INTO ROL (TIPO) VALUES ('TELEOPERADOR');
INSERT INTO ROL (TIPO) VALUES ('ANALISTA');

INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('admin@gmail.com', 'admin', 1);
INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('user@gmail.com', 'user', 2);
INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('yelmocines@gmail.com', '1234', 3);
INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('t1@gmail.com', 't1', 4);
INSERT INTO USUARIO (CORREO, CONTRASENYA, ROL) VALUES ('analista@gmail.com', 'analista', 5);

INSERT INTO ANALISIS (NOMBRE) VALUES ('ejemploAnalisis');
INSERT INTO ANALISIS (NOMBRE) VALUES ('elSegundo');

INSERT INTO EVENTO (TITULO, DESCRIPCION, FECHA, FECHACOMPRA, PRECIO, AFORO, MAXENTRADASUSUARIO, CREADOR) VALUES ('a', 'a', '2015-12-17', '2015-12-17', 1, 1, 1, 3);
INSERT INTO USUARIOEVENTO   (IDUSUARIO, NOMBRE, APELLIDO1,  DOMICILIO,      CIUDAD,     FECHANACIMIENTO,    SEXO)
                    VALUES  (2,         'FIT',  'ILLA',     'CALLE XUXES',  'CORDOBA',  '2019-07-19',       'H');
INSERT INTO ENTRADA (USUARIO, EVENTO) VALUES (3, 2);